### ISSUE TITLE
Cancel的拼写错误

### ISSUE THREAD

**Issue by isPengLu** [MuiseDestiny/zotero-figure#15]
[0.0.5: 不合法PDF路径自动重命名](https://github.com/MuiseDestiny/zotero-figure/releases/tag/0.0.5) 这页图片中cancle是错误的拼写方法，正确是Cancel。

**Comment by MuiseDestiny** [comment]
对了 这个我之前发现修订了忘记发布了哈哈哈

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/51939531/035cdeb7-8542-479b-9069-108e5fa5aa8a)


![image](https://github.com/MuiseDestiny/zotero-figure/assets/51939531/3d294dc6-e5d8-4c5a-bf6b-b5138d127f5c)


覆盖上传了，重新下载安装即可。
