### ISSUE TITLE
where is extensions.zotero.zoterofigure.path.cmd

### ISSUE THREAD

**Issue by Southwind497** [MuiseDestiny/zotero-figure#2]
I don't have wt.exe 'C:\Users\polygon\AppData\Local\Microsoft\WindowsApps\wt.exe'

**Comment by MuiseDestiny** [comment]
比如你的是windows，搜索cmd，复制它的文件地址写在这里就可以了。

**Comment by MuiseDestiny** [comment]
mac还不清楚没测试过

**Comment by Southwind497** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/786c38b8-c671-4be6-b060-fa3b11c0de06)，会有cmd的弹窗但是Figure那里没有反应欸

**Comment by MuiseDestiny** [comment]
> ![image](https://user-images.githubusercontent.com/92733066/242509957-786c38b8-c671-4be6-b060-fa3b11c0de06.png)，会有cmd的弹窗但是Figure那里没有反应欸

下载jar了吗，弹窗有输出没

**Comment by Southwind497** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/6e41416f-1077-4f57-9cef-8af822db0fbc)
![image](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/b80aa9ef-19c9-4802-a94f-2a425fc5592b)
下载jar并放在数据文件夹中了，但是弹窗没有输出

**Comment by Xiaoyuyoupang** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/103171021/b2a854b0-6c73-4a67-933e-062f75d3ba5c)
路径设置有问题吗 我也是这样的结果
![image](https://github.com/MuiseDestiny/zotero-figure/assets/103171021/75d12045-85fd-439c-883e-dfbfd018ec09)

**Comment by MuiseDestiny** [comment]
看来有问题，稍后我找人测试后发

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/51939531/dc1f7701-49de-4880-9c66-3320ead540b3)

欢迎测试-1

**Comment by LiXiong0906** [comment]
同样的问题

**Comment by MuiseDestiny** [comment]
> 同样的问题

知道原因了。我用的wt，我用cmd也不行

**Comment by LiXiong0906** [comment]
> > 同样的问题
> 
> 知道原因了。我用的wt，我用cmd也不行

等解决

**Comment by MuiseDestiny** [comment]
> > > 同样的问题
> > 
> > 
> > 知道原因了。我用的wt，我用cmd也不行
> 
> 等解决

0.0.1 不行来砍我。只需要配置java目录，cmd不用管

**Comment by LiXiong0906** [comment]
> > > > 同样的问题
> > > 
> > > 
> > > 知道原因了。我用的wt，我用cmd也不行
> > 
> > 
> > 等解决
> 
> 0.0.1 不行来砍我。只需要配置java目录，cmd不用管

我试了，确实可以了

**Comment by MuiseDestiny** [comment]
> > > > > 同样的问题
> > > > 
> > > > 
> > > > 知道原因了。我用的wt，我用cmd也不行
> > > 
> > > 
> > > 等解决
> > 
> > 
> > 0.0.1 不行来砍我。只需要配置java目录，cmd不用管
> 
> 我试了，确实可以了

可以参考readme测试下主要功能。

**Comment by Xiaoyuyoupang** [comment]
确实可以了 真是我见过处理bug最快的了 点赞！

**Comment by Southwind497** [comment]
感谢，问题解决了！
