### ISSUE TITLE
能不能像chartero那样读取图片，感觉挺快的，不用装Java

### ISSUE THREAD

**Issue by DrLiangLab** [MuiseDestiny/zotero-figure#36]
https://github.com/volatile-static/Chartero/releases

![image](https://github.com/MuiseDestiny/zotero-figure/assets/91119897/092e99fd-a222-451f-8315-4a35e9a4cf79)

谢谢！！

**Comment by Z0o0o** [comment]
> https://github.com/volatile-static/Chartero/releases
> 
> ![image](https://user-images.githubusercontent.com/91119897/260206157-092e99fd-a222-451f-8315-4a35e9a4cf79.png)
> 
> 谢谢！！

这个chartero只能读图片，有些无用的图也会读取到，figure插件还能读取表格，感觉比chartero更实用
