### ISSUE TITLE
beta 36 v0.1.2 无法手动添加图表。

### ISSUE THREAD

**Issue by yzy-lex** [MuiseDestiny/zotero-figure#45]
![CleanShot 2023-08-19 at 15 53 02@2x](https://github.com/MuiseDestiny/zotero-figure/assets/50101175/70609fa7-c3ce-4bba-a4d1-6f89086cc227)

**Comment by MuiseDestiny** [comment]
添加一个Figure x标签就添加过去了。最新beta不支持 右键菜单了

**Comment by yzy-lex** [comment]
哦吼，好咧谢谢。
