### ISSUE TITLE
无法安装插件（zptero 6.0.26, PDF Figure 0.1.2）

### ISSUE THREAD

**Issue by amnesiagreens** [MuiseDestiny/zotero-figure#49]
zetero 版本：
![zetero 版本](https://github.com/MuiseDestiny/zotero-figure/assets/20137807/6eb3fe60-634e-4e8c-980b-9d4b61fd72b4)
问题报错：
![问题报错](https://github.com/MuiseDestiny/zotero-figure/assets/20137807/39f41e0b-bf3f-410b-9308-4767e2c13852)

**Comment by characterser** [comment]
我也是
咋回事

**Comment by sdwhyxx** [comment]
0.0.7以及之前适配zotero6，之后的版本都是针对zotero7的。
要么升级zetero，要么下载老的插件版本。

**Comment by MuiseDestiny** [comment]
> 0.0.7以及之前适配zotero6，之后的版本都是针对zotero7的。 要么升级zetero，要么下载老的插件版本。

是的，谢谢回答
