### ISSUE TITLE
zotero打开pdf没有插件图标

### ISSUE THREAD

**Issue by Southwind497** [MuiseDestiny/zotero-figure#53]
![Snipaste_2023-09-04_14-17-01](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/9789cb60-be24-4e84-acd7-57ef71010158)
前段时间使用还能正常解析出图片，但今天突然找不到插件的图标了，无法启动插件

**Comment by MuiseDestiny** [comment]
软件版本，插件版本

**Comment by Southwind497** [comment]
软件版本zotero7，插件版本0.1.2

**Comment by Southwind497** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/adbff756-9f8f-4a9b-8146-ab66910c6832)
尝试disable Better notes插件可以正常使用了
![image](https://github.com/MuiseDestiny/zotero-figure/assets/92733066/ed46c356-31ca-4f50-b8dd-ca840c8fb504)
应该是插件出现了冲突

**Comment by MuiseDestiny** [comment]
升级一下better notes呢。一般不会冲突的

**Comment by skipskipthree** [comment]
禁用disable better notes 仍然没有图标，请问这个怎么解决
