### ISSUE TITLE
一直卡在reading json  而且有时候明明识别到图片 但是在zotero 的里面却没有图片

### ISSUE THREAD

**Issue by Qwsetygfhuhhf** [MuiseDestiny/zotero-figure#7]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/113030478/3dd5b55c-930b-46fc-9371-aad189c30e68)

**Comment by MuiseDestiny** [comment]
看下readme改一下编码

**Comment by Qwsetygfhuhhf** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/113030478/e962ccaf-419f-40da-a13b-51a4b89b86fa)
已经按照readme 进行修改，还是不行，zotero 文件夹内figure 文件夹内有生成的图片，但是软件内没有显示出来。


“[{
  "renderDpi": 300,
  "name": "1",
  "page": 1,
  "figType": "Figure",
  "regionBoundary": {
    "x1": 91.92,
    "y1": 478.79999999999995,
    "x2": 509.03999999999996,
    "y2": 698.4
  },
  "caption": "Fig. 1 | Structure design. Biomimetic concept of sub-nanometer-sized Na+ transport zones constructed by adjacent –COO− groups and COF inwalls (the purple and red spheres and cyan ovals denote sodium and oxygen and TFSI−, respectively, and the cyan sticks and molecular structures denote the covalent organic framework).",
  "imageText": ["O", "–OOC", "–OOC", "COO–", "COO–", "COO–", "–OOC", "COO–", "Na+", "(6.7", "–", "11.6", "Å)", "COO–", "–OOC", "Sub-nanometer-sized", "transport", "zone", "–COO–", "modified", "inwall", "Sub-nanochannels", "of", "biomembrane", "Na+/K+", "Cl–"],
  "renderURL": "E:\\Zotero\\zoterofigure\\figure/Yan 等 - 2023 - Bioinspired design of Na-ion conduction channels i-Figure1-1.png",
  "captionBoundary": {
    "x1": 39.68476867675781,
    "y1": 710.5701293945312,
    "x2": 561.3623046875,
    "y2": 724.5923461914062
  }
}, {
  "renderDpi": 300,
  "name": "6",
  "page": 6,
  "figType": "Figure",
  "regionBoundary": {
    "x1": 60.0,
    "y1": 47.76,
    "x2": 541.1999999999999,
    "y2": 376.08
  },
  "caption": "Fig. 6 | Electrochemical window and Na plating/stripping of COF-QSSEs. a LSV profiles of SS|TPBD-QSSE|Na and SS|TPDBD-CNa-QSSE|Na asymmetric cells. b Calculated HOMO and LUMO values of TPBD and TPDBD based on DFT calculations. c Rate performance of Na plating/stripping for Na|QSSE|Na at 25 ± 1 °C and 0.01, 0.03, 0.04, 0.1, 0.2, 0.5, 0.6, and 0.8mA cm−2. d Na plating/stripping of Na| QSSE|Na at a current density of 0.01mA cm−2 and 25 ± 1 °C for 900h and 2 h per cycle (the inset shows the time-division plating/stripping curves).",
  "imageText": [],
  "renderURL": "E:\\Zotero\\zoterofigure\\figure/Yan 等 - 2023 - Bioinspired design of Na-ion conduction channels i-Figure6-1.png",
  "captionBoundary": {
    "x1": 39.685001373291016,
    "y1": 385.6064453125,
    "x2": 557.4326782226562,
    "y2": 419.58489990234375
  }
}, {
  "renderDpi": 300,
  "name": "2",
  "page": 2,
  "figType": "Figure",
  "regionBoundary": {
    "x1": 91.44,
    "y1": 49.92,
    "x2": 510.47999999999996,
    "y2": 323.28
  },
  "caption": "Fig. 2 | Physical characterizationof theCOFs. a FTIR spectraof TPBD, TPDBD, BD, DBD, and TP. b Partial unit structures of TPBD and TPDBD. c 13C CP-MAS solid-state NMR spectra of TPBD, TPDBD, and TP. d XPS C 1s spectra of TPBD, TPDBD, and TPDBD-CNa. e XPS O 1s spectra of TPBD, TPDBD, and TPDBD-CNa. f SEM image of TPDBD.",
  "imageText": ["O=C-ONa", "(a)", "533.18", "O=C-ONa", "(b)", "531.97", "f", "a", "g", "d", "e", "b", "c", "h", "i", "TPBD", "TPDBD", "OHO", "O", "OHO", "OH", "O", "HO", "O", "HO", "OH", "O", "H", "N", "HN", "NH", "O", "O", "O", "H", "N", "HN", "NH", "O", "O", "O", "c", "d", "e", "b", "f", ".)", "(a", ".u", "ns", "ity", "TPDBD-CNaIn", "te", "Binding", "energy", "(eV)", "C=C", "C=O", "C-N", "HO-C=O", "288.66", "NaO-C=O", "288.41", "TPBDC", "1s", "TPDBD", "290", "288", "286", "284", "282", "a", "C=O", "1639", "CH=O", "C-N", "1256", "Ar(C=C)", "1450", "C=C", "1586", "NH2", "-COOHTPBD", "(%", ")", "an", "ce", "sm", "itt", "Tr", "an", "Wavenumber", "(cm", "1)", "BD", "DBD", "TP", "TPDBD", "4000", "3500", "3000", "2500", "2000", "1500", "1000", "500", "1", "μm", "TPDBD-CNa", "Binding", "energy", "(eV)", "C=O", "531.06", ".)", "(a", ".u", "ns", "ity", "In", "te", "TPDBD", "O=C-OH", "(b)", "532.30", "C=O", "531.23", "O=C-OH", "(a)", "533.43", "C=O", "O", "1s", "TPBD", "538", "536", "534", "532", "530", "528", "h", "i", "112.9", "126.3", "168.2", "-COOH", "144.2", "C=O", "(TP)", "184.5", "e117.2", "d", "120.7", "138.0", "c", "127.8", "g", "107.5", "f", "148.5", "b", "188.3", "a", "Chemical", "shift", "(ppm)", "TPCDCl3", "TPBD", "TPDBD", "128.8", "122.6", "138.6", "200", "150", "100", "50"],
  "renderURL": "E:\\Zotero\\zoterofigure\\figure/Yan 等 - 2023 - Bioinspired design of Na-ion conduction channels i-Figure2-1.png",
  "captionBoundary": {
    "x1": 39.68499755859375,
    "y1": 334.4694519042969,
    "x2": 554.759521484375,
    "y2": 358.4694519042969
  }
}, {
  "renderDpi": 300,
  "name": "7",
  "page": 7,
  "figType": "Figure",
  "regionBoundary": {
    "x1": 60.239999999999995,
    "y1": 49.68,
    "x2": 540.48,
    "y2": 390.0
  },
  "caption": "Fig. 7 | Ex-situ postmortemXPS and SEMcharacterizations. a XPS C 1s, O 1s, F 1s, andNa 1s spectra of the TPDBD-CNa-QSSE/TPBD-QSSE inNa||Na cells over 20cycles at 0.02mA cm−2 and 25 ± 1 °C and TPDBD-CNa-NaTFSI/TPBD-NaTFSI. b XPS C 1s, O 1s, F 1s, and Na 1s depth profiles of cycled Na metal over 20 cycles at 0.02mA cm−2 and 25 ± 1 °C in a Na|TPDBD-CNa-QSSE|Na symmetric cell. SEM images of cycled membranes of the TPBD-QSSE (c) and TPDBD-CNa-QSSE (d) over 20 cycles at",
  "imageText": ["Binding", "energy", "(eV)", "Binding", "energy", "(eV)", "Binding", "energy", "(eV)", "Binding", "energy", "(eV)", "C", "1s", "O", "1sC", "1s", "F", "1sO", "1s", "F", "1s", "Na", "1s", "Na", "1s", "Binding", "energy", "(eV)", "Na(NaTFSI)", "Na2CO3", "1077", "1074", "1071", "1068", "Na2CO3", "NaF/", "Na2O", "1074", "1072", "1070", "1068", "Binding", "energy", "(eV)", "696", "692", "688", "684", "NaFC-F", "690", "687", "684", "681", "Binding", "energy", "(eV)", "RO-C=O", "Na2CO3", "C=O", "SOx", "537", "534", "531", "528", "Na2O", "Na2CO3", "C=O", "RO-C=ONa", "Auger", "SOx", "540", "536", "532", "528", "b", "Binding", "energy", "(eV)", "C=O", "TPDBD-CNa-QSSE", "Na2CO3", "F(NaTFSI)", "RO-C=O", "TPDBD-CNa-NaTFSI", "TPBD-QSSE", "TPBD-NaTFSI", "294", "291", "288", "285", "282", "0", "nm", "40", "nm", "100", "nm", "200", "nm", "C-F", "Na2CO3", "RO-C=O", "C=O", "292", "288", "284", "280", "a", "f", "Cycled", "Na", "metal", "Flat-shape", "Gathering", "type", "5", "μm", "Branching", "type", "e", "10", "μm", "5", "μm", "Cracks", "d", "Cracks", "c", "10", "μm", "Cycled", "electrolyte", "membranes"],
  "renderURL": "E:\\Zotero\\zoterofigure\\figure/Yan 等 - 2023 - Bioinspired design of Na-ion conduction channels i-Figure7-1.png",
  "captionBoundary": {
    "x1": 39.68364715576172,
    "y1": 399.5529479980469,
    "x2": 554.8302001953125,
    "y2": 433.5308532714844
  }
}]
""

**Comment by cjlCMU** [comment]
我也遇到了相同情况

**Comment by cjlCMU** [comment]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/102497540/10704a29-1cc8-4480-a140-4013a4ac8572)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-figure/blob/bootstrap/README.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by MuiseDestiny** [comment]
编码错误，首选项更改一下就好了。
比如你的json编码是utf-8，但插件以gbk读取，图片路径就是错误的。所以导入不成功。

**Comment by MuiseDestiny** [comment]
我下一个版本加入自动判断编码。

**Comment by MuiseDestiny** [comment]
已经更新，无需任何配置，更新后解决。
