### ISSUE TITLE
Zotero7 无法提取图片

### ISSUE THREAD

**Issue by ghwld** [MuiseDestiny/zotero-figure#74]
可以弹出cmd弹窗，但是没有图片解析出来。
![QQ图片20240416195437](https://github.com/MuiseDestiny/zotero-figure/assets/167201803/9de8eb58-b85c-446d-ad4e-f17d20cd8694)
![image](https://github.com/MuiseDestiny/zotero-figure/assets/167201803/71e3a3b0-640f-4e13-a1e5-d87ce6755a2c)

**Comment by MuiseDestiny** [comment]
试试别的，不是所有pdf都能很好支持的。
