### ISSUE TITLE
PDFFigures如何提取PDF中的文字

### ISSUE THREAD

**Issue by adffend** [MuiseDestiny/zotero-figure#75]
感谢制作和分享这么好的插件。向您请教一个问题。 我看PDFFigre2的github介绍，它是可以提取section和text的，加上-g参数。 但是我在python中调用总是报错，网上也没有找到相关介绍。 请问您知道如何实现吗？ 谢谢。

**Comment by MuiseDestiny** [comment]
试过，是可以的，但是精度不是很好。不建议继续尝试。

**Comment by adffend** [comment]
好的，谢谢
