### ISSUE TITLE
增加注释失败

### ISSUE THREAD

**Issue by woodGHub** [MuiseDestiny/zotero-figure#79]
![image](https://github.com/MuiseDestiny/zotero-figure/assets/44263447/04f70565-15d8-4614-baa6-7593c96e8df6)
![image](https://github.com/MuiseDestiny/zotero-figure/assets/44263447/4df72889-ec60-405d-9318-62e3c3039bc0)
![image](https://github.com/MuiseDestiny/zotero-figure/assets/44263447/0d9fecff-61ec-4144-86bd-8f5be3ef1951)

**Comment by MuiseDestiny** [comment]
插件已更新，请注意更新
