### ISSUE TITLE
建议：使用环境变量获取JAVA路径，最小化/隐藏运行窗口

### ISSUE THREAD

**Issue by GFDGIT** [MuiseDestiny/zotero-figure#9]
大佬你好，首先感谢你开发这个插件。
我想提点建议，希望可以提升使用体验：
- 使用JAVA_HOME环境变量获取JAVA路径，这样可以简化配置操作，也避免配置错误。
- 隐藏运行窗口，我只知道，windows上可以用`cmd /c start /b xxx`最小化窗口并后台运行，其他系统就不清楚了。

**Comment by MuiseDestiny** [comment]
隐藏研究了好久没研究出来，试过你说的。

**Comment by MuiseDestiny** [comment]
而且cmd也不能直接用，也需要exe路径，这个无法简化。

**Comment by GFDGIT** [comment]
> 而且cmd也不能直接用，也需要exe路径，这个无法简化。

可能`start`也需要具体的exe路径？

或者用`powershell -windowstyle hidden`，或者调用vbs，就可以实现完全隐藏窗口的后台运行了。

**Comment by MuiseDestiny** [comment]
你可以在runjs试试

**Comment by GFDGIT** [comment]
> 你可以在runjs试试 

😅我不懂编程，只是查到有这么些方法，还是得等大佬有空来研究下能不能行得通。

**Comment by Ninecr** [comment]
使用javaw运行就不会弹出命令行窗口了。

**Comment by MuiseDestiny** [comment]
> 使用javaw运行就不会弹出命令行窗口了。

哇 我试试

**Comment by MuiseDestiny** [comment]
> 使用javaw运行就不会弹出命令行窗口了。

可行
