### ISSUE TITLE
This plugin causes comments within zotero7 to not show up

### ISSUE THREAD

**Issue by MXS81** [MuiseDestiny/zotero-figure#90]
Using this plugin causes in-software annotations not to be displayed in the sidebar, including the highlighted portion of the body annotations. The annotations are actually generated.

**Comment by dstillman** [comment]
We received another report that this plugin is causing annotations not to show up:

https://forums.zotero.org/discussion/119784/the-annotations-in-the-pdf-have-disappeared

@MuiseDestiny, could you fix this and push a new version?

**Comment by MuiseDestiny** [comment]
In fact, the plugin provides an option to only display the figure/table annotation, which will hide the user's annotations, and the user may forget to turn off this option. For this reason, I added the following code in latest version to automatically help the user switch to the appropriate view:

```js
Zotero.Reader.registerEventListener("renderTextSelectionPopup", (event) => {
  const {reader} = event
  if (this.view == "Figure") {
    this.switchToView(reader, "All")
  }
})
```
